import React from 'react';
import { useParams, Link } from 'react-router-dom';

const apiData: Record<string, {
  name: string; category: string; status: string;
  headline: string; description: string;
  dataPoints: string[]; sampleInsight: string;
  endpoint: string;
}> = {
  weather: {
    name: 'Weather Engine', category: 'Environment', status: 'Active',
    headline: 'Atmospheric intelligence for your day.',
    description: 'The Weather Engine pulls real-time atmospheric data and cross-references it with your schedule, mood, and health patterns to surface precisely timed recommendations — from the best window for a run to when to plan outdoor meetings.',
    dataPoints: ['Temperature & humidity', 'UV index', 'Wind & rain probability', 'Pollen count', 'Sunrise & sunset times', 'Hourly forecasts (72h)'],
    sampleInsight: 'Feels like 22°C this afternoon with low humidity. Optimal for outdoor activity 3–5 PM. Avoid if sensitive to pollen (high today).',
    endpoint: 'GET /v1/intelligence/weather',
  },
  geolocation: {
    name: 'Spatial Awareness', category: 'Location', status: 'Active',
    headline: 'Context is everything.',
    description: 'Geolocation data is the backbone of personalisation. Life OS uses your location to filter news, adjust food and fitness recommendations, calculate commute windows, and understand your environmental context without storing sensitive data.',
    dataPoints: ['City & neighbourhood', 'Timezone auto-detection', 'Commute origin/destination', 'Nearby amenities', 'Air quality index', 'Local event density'],
    sampleInsight: 'You are in Mumbai. AQI is moderate (87). Masks advisable outdoors. Traffic surge expected 6–8 PM on your usual route.',
    endpoint: 'GET /v1/intelligence/location',
  },
  news: {
    name: 'News Intelligence', category: 'Media', status: 'Active',
    headline: 'Only what actually matters to you.',
    description: 'Life OS doesn\'t show you a feed — it filters global narratives through your context and interests, distilling what is actually relevant to your decisions today. Stress-inducing, irrelevant content is automatically deprioritised.',
    dataPoints: ['Local & global headlines', 'Topic relevance scoring', 'Sentiment analysis per article', 'Source credibility weighting', 'Reading time estimate', 'Impact-to-life scoring'],
    sampleInsight: '3 articles relevant to your domain. 1 financial update affecting your sector. 0 stressful headlines flagged for evening reading.',
    endpoint: 'GET /v1/intelligence/news',
  },
  nlp: {
    name: 'NLP / Text Analysis', category: 'AI / Language', status: 'Active',
    headline: 'Your words, decoded.',
    description: 'Life OS reads your notes and journal entries using natural language processing to detect emotional tone, stress markers, recurring concerns, and focus themes. Over time, it builds a pattern map of your mental state.',
    dataPoints: ['Mood score (0–100)', 'Stress level detection', 'Recurring topic clusters', 'Sentiment trend (7 & 30 day)', 'Vocabulary complexity', 'Energy & motivation markers'],
    sampleInsight: 'Mood: +78 today. Recurring theme this week: "deadlines". Stress peaked Tuesday. Suggest a mindfulness block before your 3 PM meeting.',
    endpoint: 'POST /v1/intelligence/nlp/analyse',
  },
  calendar: {
    name: 'Temporal Logic', category: 'Scheduling', status: 'Beta',
    headline: 'Time, finally working for you.',
    description: 'The Calendar engine analyses your existing commitments and finds the highest-value time pockets for deep work, rest, and reactive tasks. It learns your energy rhythms and suggests restructuring where possible.',
    dataPoints: ['Meeting density score', 'Focus block detection', 'Recovery window mapping', 'Deadline proximity alerts', 'Context-switch frequency', 'Energy alignment score'],
    sampleInsight: 'You have 3 meetings today. Best deep-work window: 2:30–5:00 PM. Consider moving your 4 PM check-in — it breaks a 90-min flow state.',
    endpoint: 'GET /v1/intelligence/calendar',
  },
  food: {
    name: 'Food Intelligence', category: 'Nutrition', status: 'Beta',
    headline: 'Eat with context.',
    description: 'Food recommendations are generated by layering weather data, detected mood, activity level, and time of day. Life OS suggests meals that support your energy arc throughout the day, not just what tastes good.',
    dataPoints: ['Meal timing optimisation', 'Macronutrient alignment', 'Hydration reminders', 'Mood-food correlation', 'Local cuisine suggestions', 'Fasting window tracking'],
    sampleInsight: 'Post-workout hydration low. High-protein lunch aligned with your 2 PM deep-work block. Avoid heavy carbs before tonight\'s 8 PM session.',
    endpoint: 'GET /v1/intelligence/food',
  },
  fitness: {
    name: 'Bio-Sync Health', category: 'Fitness', status: 'Beta',
    headline: 'Move when it matters.',
    description: 'Fitness recommendations are generated from your activity level, sleep quality, mood, and weather. Rather than prescribing rigid routines, Life OS adapts daily to when your body is actually ready to perform.',
    dataPoints: ['Activity level (steps/active mins)', 'Sleep quality score', 'Workout window recommendation', 'Recovery vs. training balance', 'Heart rate zone guidance', 'Streak & consistency tracking'],
    sampleInsight: 'Recovery score: 71. Light activity recommended. Optimal workout window: 5–6:30 PM. Rest tomorrow if streak continues above 5 days.',
    endpoint: 'GET /v1/intelligence/fitness',
  },
  transport: {
    name: 'Transport Engine', category: 'Mobility', status: 'Active',
    headline: 'Leave at the right moment.',
    description: 'The Transport engine monitors traffic conditions, public transit delays, and weather to recommend the smartest departure times. It reduces commute friction so you arrive with cognitive and physical reserves intact.',
    dataPoints: ['Real-time traffic conditions', 'Commute duration estimates', 'Transit delay alerts', 'Weather impact on route', 'Optimal departure window', 'Weekly commute trend'],
    sampleInsight: 'Traffic on your usual route is 14 min above average. Leave by 8:40 AM to arrive on time. Rain likely — account for slower transit.',
    endpoint: 'GET /v1/intelligence/transport',
  },
};

const APIDetailPage: React.FC = () => {
  const { slug } = useParams<{ slug: string }>();
  const api = slug ? apiData[slug] : null;

  if (!api) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center py-32">
        <p style={{ fontFamily: "'Doto', monospace" }} className="text-[32px] font-bold text-stone-900 mb-4">MODULE NOT FOUND</p>
        <Link to="/apis" className="text-[13px] text-stone-400 hover:text-stone-700 transition-colors">← Back to APIs</Link>
      </div>
    );
  }

  return (
    <div className="flex-1">
      <section className="pt-14 pb-10 border-b border-stone-200">
        <div className="max-w-6xl mx-auto px-8">
          <Link to="/apis" className="text-[12px] font-medium text-stone-400 hover:text-stone-700 transition-colors inline-flex items-center gap-1 mb-8">
            ← All APIs
          </Link>
          <div className="flex items-start justify-between">
            <div>
              <span className="text-[10px] font-semibold tracking-[0.12em] uppercase text-stone-400">{api.category}</span>
              <h1 style={{ fontFamily: "'Doto', monospace" }} className="text-[48px] font-bold text-stone-900 mt-2 mb-4 leading-tight">
                {api.name.toUpperCase()}
              </h1>
              <p className="text-[15px] text-stone-500 font-medium">{api.headline}</p>
            </div>
            <span className={`text-[10px] font-semibold tracking-[0.08em] uppercase px-3 py-1.5 rounded-full border mt-2 ${api.status === 'Active' ? 'border-stone-200 text-stone-500 bg-stone-50' : 'border-amber-200 text-amber-600 bg-amber-50'}`}>
              {api.status}
            </span>
          </div>
        </div>
      </section>

      <section className="py-14">
        <div className="max-w-6xl mx-auto px-8">
          <div className="flex items-start gap-12">

            <div className="flex-1 flex flex-col gap-10">
              <div>
                <p className="text-[10px] font-semibold tracking-[0.12em] uppercase text-stone-400 mb-4">About</p>
                <p className="text-[14px] text-stone-500 leading-[1.85] max-w-lg">{api.description}</p>
              </div>

              <div className="bg-white border border-stone-200 rounded-2xl p-7">
                <p className="text-[10px] font-semibold tracking-[0.12em] uppercase text-stone-400 mb-5">Live Insight Sample</p>
                <div className="flex items-start gap-3">
                  <div className="w-1.5 h-1.5 rounded-full bg-stone-700 animate-pulse mt-1.5 shrink-0" />
                  <p className="text-[14px] text-stone-700 leading-relaxed">{api.sampleInsight}</p>
                </div>
              </div>

              <div className="bg-white border border-stone-200 rounded-2xl p-7">
                <p className="text-[10px] font-semibold tracking-[0.12em] uppercase text-stone-400 mb-4">Endpoint</p>
                <code style={{ fontFamily: 'monospace' }} className="text-[13px] text-stone-700 bg-stone-50 border border-stone-200 px-4 py-2.5 rounded-xl block">
                  {api.endpoint}
                </code>
              </div>
            </div>

            <div className="shrink-0 w-[280px]">
              <div className="bg-white border border-stone-200 rounded-2xl p-7">
                <p className="text-[10px] font-semibold tracking-[0.12em] uppercase text-stone-400 mb-5">Data Points</p>
                <div className="flex flex-col gap-3">
                  {api.dataPoints.map((point) => (
                    <div key={point} className="flex items-center gap-3">
                      <div className="w-1 h-1 rounded-full bg-stone-400 shrink-0" />
                      <span className="text-[13px] text-stone-600">{point}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>

          </div>
        </div>
      </section>
    </div>
  );
};

export default APIDetailPage;
